apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matomo.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.redis.enabled }}
        - args:
            - for i in {30..0}; do redis-cli -h ${MATOMO_CACHE_HOST} -a ${MATOMO_CACHE_PASSWORD} ping &> /dev/null;
              if [[ $? == 0 ]]; then
              echo "Connection to Redis established."; exit 0; fi;
              echo "Redis init process in progress..."; sleep 1; done;
              echo "No connection to Redis could be established!"; exit 1;
          command:
            - /bin/bash
            - -c
          envFrom:
            - secretRef:
                name: {{ template "matomo.fullname" . }}
          image: library/redis
          imagePullPolicy: Always
          name: redis-init
          resources:
            requests:
              memory: 50Mi
        {{- end }}
        {{- if .Values.mariadb.enabled }}
        - args:
            - for i in {30..0}; do mysql -h${MATOMO_DATABASE_HOST} -u${MATOMO_DATABASE_USER} -p${MATOMO_DATABASE_PASSWORD} -N -e "SELECT 1" &> /dev/null;
              if [[ $? == 0 ]]; then
              echo "Connection to MariaDB established."; exit 0; fi;
              echo "MariaDB init process in progress..."; sleep 1; done;
              echo "No connection to MariaDB could be established!"; exit 1;
          command:
            - /bin/bash
            - -c
          envFrom:
            - secretRef:
                name: {{ template "matomo.fullname" . }}
          image: library/mariadb
          imagePullPolicy: Always
          name: mariadb-init
          resources:
            requests:
              memory: 50Mi
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ template "matomo.fullname" . }}
          env:
            - name: MATOMO_WEBSITE_NAME
              value: {{ .Values.matomoWebsiteName | quote }}
            - name: MATOMO_WEBSITE_HOST
              value: {{ include "matomo.host" . | quote }}
            - name: MATOMO_SKIP_BOOTSTRAP
              value: {{ default (ternary "no" "yes" .Release.IsInstall) .Values.matomoSkipBootstrap | quote }}
            - name: MATOMO_DATABASE_HOST
              value: {{ include "matomo.databaseHost" . | quote }}
            - name: MATOMO_DATABASE_PORT_NUMBER
              value: {{ include "matomo.databasePort" . | quote }}
            - name: MATOMO_DATABASE_NAME
              value: {{ include "matomo.databaseName" . | quote }}
            - name: MATOMO_DATABASE_USER
              value: {{ include "matomo.databaseUser" . | quote }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.databaseSecretName" . }}
                  key: mariadb-password
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: matomo-data
              mountPath: /bitnami/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: matomo-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "matomo.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
