{{- if not (or .Values.mariadb.enabled .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" ( include "matomo.fullname" . ) }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
