{{- if and (include "matomo.host" .) .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "matomo.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.hostPath }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
