{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
data:
  matomo-password: {{ b64enc (include "matomo.password" .) | quote }}
{{- end }}
